name: tdmpc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.9.0
  - torchvision=0.10.0
  - torchaudio=0.9.0
  - cudatoolkit=11.3
  - pip
  - pip:
    - setuptools==65.5.0 
    - "wheel<0.40.0"
    - termcolor
    - omegaconf
    # - gym==0.21.0  install it with 'pip install "pip<24.1"' and 'pip install gym==0.21.0' later
    - dm-control==0.0.403778684
    - pandas
    - wandb
    - moviepy
    - imageio

